Fix/auth forms validation
hpi-studyu/studyu pull request #552
Opened 2023-12-18 14:02 UTC by johannesvedder

- fix: no more issues with form validations at login and registration pages
- feat: added login and registration error messages

2023-12-21 01:41 UTC, hig-dev requested changes
Looks good. One thing that I noticed was:

1. Go to register user
2. Fill password
3. Fill password confirmation
4. Accept terms

Now the register buttons gets activated although the email is empty.

2023-12-21 01:41 UTC, hig-dev commented on designer_v2/lib/features/auth/auth_form_controller.dart
> +  final FormControl<String> testControl = FormControl();
```suggestion
```

Remove this

2023-12-22 08:37 UTC, johannesvedder commented
> Looks good. One thing that I noticed was:
> 
>     1. Go to register user
> 
>     2. Fill password
> 
>     3. Fill password confirmation
> 
>     4. Accept terms
> 
> 
> Now the register buttons gets activated although the email is empty.

Nice catch 👍 Should be fixed now.

2024-01-01 14:42 UTC, hig-dev approved these changes
Great

2024-01-10 13:29 UTC, merged