Feat/collapsedashboardmenu: Make dashboard page responsive
hpi-studyu/studyu pull request #557
Opened 2023-12-21 00:54 UTC by hig-dev

- Collapses dashboard drawer if horizontal space is too low
- Make width of search bar responsive

Addresses: #556

2023-12-22 11:58 UTC, johannesvedder requested changes
Great addition for smaller screen widths! I like it. There are just some issues that I noticed:
- Small QoL improvement: Close the drawer in compact mode after a selection has been made
- The available space for the "Created" column becomes smaller and smaller as the page width decreases until the column has disappeared completely.
- Similar behavior with the most right columns as they are just cut off with decreasing screen widths. This does not only impair visual appearance, but also has an impact on usability, as the menu can not be used on smaller screen widths with non-collapsed drawer. To counteract this, we would either need to change the compact threshold to a very high value, or add a horizontal scrollbar. I would recommend the latter.

2023-12-22 11:58 UTC, johannesvedder commented on designer_v2/lib/features/dashboard/dashboard_scaffold.dart
> +        drawer: isCompact ? AppDrawer(title: tr.studyu) : null,
Using the logo might be more appropriate here instead of showing the (unthemed) text.

2023-12-22 12:05 UTC, johannesvedder commented on designer_v2/lib/features/dashboard/dashboard_scaffold.dart
> +        drawer: isCompact ? AppDrawer(title: tr.studyu) : null,
See: https://github.com/hpi-studyu/studyu/pull/560

2024-01-01 17:37 UTC, hig-dev commented on designer_v2/lib/features/app_drawer.dart
>    void didUpdateWidget(AppDrawer oldWidget) {
Commit b01544bd breaks the update of the selected route.
That's why I reverted it. 

@johannesvedder : Do you have a better idea for the update of the selected route that works with a `const AppDrawer`?

2024-01-01 17:41 UTC, hig-dev commented
> * Small QoL improvement: Close the drawer in compact mode after a selection has been made

Done.

2024-01-10 22:27 UTC, closed without merging

2024-01-10 22:27 UTC, hig-dev commented
Will be merged with #555