Feat/study closing: Add option to close a study
hpi-studyu/studyu pull request #601
Opened 2024-04-03 04:51 UTC by hig-dev

This PR adds the feature to close a study. It is not possible to re-open a study. No new participants will be able to enroll in a closed study.

- [ ] Database: Add "is_closed" column to study table
- [ ] Database: Add policy to restrict joining a closed study
- [ ] App: Do not show closed studies in study selection
- [ ] App: Show dialog if user tries to join a closed study
- [ ] Designer: Use study status to show state of study (running, darf, closed)
- [ ] Designer: Adapt study duplicate function
- [ ] Designer: Add feature to close study using modal actions
- [ ] Designer: Add banner to recruit page for closed study

2024-04-10 11:31 UTC, johannesvedder requested changes

2024-04-16 17:05 UTC, hig-dev commented on database/studyu-schema.sql
> +));
Good catch. Yes, the `upsert` operation in `StudySubject.save()` is problematic.

I would suggest to replace the upsert with explicit insert or update operations.

2024-04-16 17:51 UTC, hig-dev commented on database/studyu-schema.sql
> +));
See: https://github.com/hpi-studyu/studyu/pull/601/commits/62243d8d19227d85a4dcf40bbdfe0fc4e0a42f52

2024-05-25 14:40 UTC, johannesvedder requested changes

2024-05-25 14:40 UTC, johannesvedder commented on core/lib/src/models/tables/study.dart
> +  bool isClosed = false;
rename to `closed`

2024-05-25 14:40 UTC, johannesvedder commented on core/lib/src/models/tables/study.dart
> +      final response = await env.client.from(tableName).select().eq('participation', 'open').eq("is_closed", false);
.

2024-05-25 14:40 UTC, johannesvedder commented on core/lib/src/models/tables/study.dart
.

2024-05-25 14:40 UTC, johannesvedder commented on database/migration/migrate-close_study.sql
> +));
rename file

2024-05-25 14:40 UTC, johannesvedder commented on database/studyu-schema.sql
> +    is_closed boolean DEFAULT false NOT NULL,
.

2024-05-25 14:40 UTC, johannesvedder commented on database/studyu-schema.sql
> +));
test this again

2024-05-25 14:40 UTC, johannesvedder commented on designer_v2/lib/domain/study.dart
> +    copy.isClosed = false;
.

2024-05-25 14:40 UTC, johannesvedder commented on designer_v2/lib/localization/app_en.arb
> +  "study_status_closed_description": "This study has been completed.\nNo new participants will be able to enroll.",
..will not be able..

2024-05-25 14:40 UTC, johannesvedder commented on designer_v2/lib/localization/app_en.arb
> +  "dialog_study_close_description": "Are you sure that you want to close participation for this study? No new participants will be able to enroll.",
.

2024-05-25 14:40 UTC, johannesvedder commented on designer_v2/lib/localization/app_en.arb
> +  "banner_study_closed_description": "No new participants will be able to enroll in this study.",
.

2024-05-25 17:42 UTC, johannesvedder requested changes

2024-05-25 17:42 UTC, johannesvedder commented on app/lib/screens/study/onboarding/study_selection.dart
>                                  await navigateToStudyOverview(context, study);
are closed studies shown in study selection? should we make them invisible instead?

2024-06-19 11:07 UTC, johannesvedder approved these changes

2024-06-19 11:11 UTC, merged