Feature/filter
hpi-studyu/studyu pull request #680
Opened 2024-08-25 21:07 UTC by rajuAhmed1705

2024-08-27 16:24 UTC, ibrahimozkn requested changes
1. After changing any filter, if the resulting study list is empty, it becomes impossible to access the filtering options to revert the applied changes.

![image](https://github.com/user-attachments/assets/658fcc6c-322e-4cbc-870f-0b6d39b121a3)


2. Choosing both Everyone and Invite Only options in participation filter is duplicating the existing studies in the list
![image](https://github.com/user-attachments/assets/71147863-4651-4210-9d3d-322c16a5f613)

2024-09-25 09:36 UTC, ibrahimozkn submitted a review, later dismissed

2024-10-01 14:50 UTC, johannesvedder commented
@ibrahimozkn could you check the warnings? https://github.com/hpi-studyu/studyu/actions/runs/10976108923/job/30476497785?pr=680

2024-10-02 11:29 UTC, johannesvedder commented
The e2e test seems to be broken, not sure if this is related to this PR though

2024-10-02 11:44 UTC, johannesvedder commented
Some remarks:

- I would still show the sorting arrow next to the name and then the filter icon. Because currently you don't expect that you can still sort the items and only see the filter icon. But the filter menu does not open when you click on the name, even though the icon hover effect appears. So for now I would remove the onclick from the column name, add sorting arrow and filtering icon and have onclick actions with hover effect on both icons.
  - For long term this will probably become really messy to show two symbols next to each column. I like supabase's approach to have a single sort and filter option on the top for all columns. This looks way cleaner.
![grafik](https://github.com/user-attachments/assets/0f046458-9277-47a6-a1c3-70443669670f)
- We should think about storing sorting and filtering selections in the database for each user to make these settings persistent
- Since you can only filter by one item right now, radio buttons are a better fit than checkboxes which indicates that a user can select multiple items
- Replace the button label "Filter" with a clearer message. "Apply filter" or just "Apply" fits better 
![grafik](https://github.com/user-attachments/assets/a0515c4b-9730-4194-b450-71668c0abb25)
- When the filter menu is shown, no other menus/popups/buttons of the page behind should be clickable. A click next to the menu should close the popup. Otherwise this leads to a weird behavior, e.g. when you click on a study while the popup is open: 
![grafik](https://github.com/user-attachments/assets/c991b90c-13ce-419a-bedc-ad4b389c3716)

2025-05-26 22:43 UTC, closed without merging